/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PhilosophyOfJava;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("OKK,,,, let's begin");
    	System.out.println("BEGIN...");
    	
        return false;
    }
}
